### ISSUE TITLE
Breaking changes in wagtail 1.1

### ISSUE THREAD

**Issue by ernlel** [bashu/wagtail-embedvideos#15]
After updating Wagtail to version 1.1 wagtail-embedvideos component not working because all wagtailimages urls moved into a namespace.

Solution:

in file wagtail_embed_videos/templates/wagtail_embed_videos/embed_videos/add.html
replace line 19
`window.chooserUrls.imageChooser = "{% url 'wagtailimages_chooser' %}";`
with
`window.chooserUrls.imageChooser = "{% url 'wagtailimages:chooser' %}";`

in file wagtail_embed_videos/templates/wagtail_embed_videos/embed_videos/edit.html
replace line 20
`window.chooserUrls.imageChooser = "{% url 'wagtailimages_chooser' %}";`
with
`window.chooserUrls.imageChooser = "{% url 'wagtailimages:chooser' %}";`

however after this changes wagtail-embedvideos not compatible with Wagtail 1.0

**Comment by SalahAdDin** [comment]
Please, do a PR :D
