### ISSUE TITLE
Migration's problem with new version

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#19]
Hi man

I test the new release version and i have a  problem with migrations:
`django.db.utils.ProgrammingError: «wagtail_embed_videos_embedvideo» relation already exits`

Yes, exists, i have this relation because i are using wagtail embed videos since many months, then, wha can i do ?

Thanks.

**Comment by DiogoMarques29** [comment]
I suggest you drop your DB and run migrations again.

**Comment by SalahAdDin** [comment]
Well, i do fake the first migration and do the next migrations, but shouldn't be necessary do this man.
