### ISSUE TITLE
Support for custom image

### ISSUE THREAD

**Issue by drwlrsn** [bashu/wagtail-embedvideos#20]
I noticed that right now if one uses a custom image model, uploading a thumbnail image will fail. I have made some changes here: drwlrsn/wagtail-embedvideos@82e4ee881dc4bdd9098097f0c46e2e4acbe53fad.

If that looks good, I can submit a pull request.

**Comment by SalahAdDin** [comment]
Yes, i update now django-embed-videos, and see good.
Please add this feature @rmartins90

**Comment by DiogoMarques29** [comment]
Hi @drwlrsn 
It looks good indeed. Have you tested it and it works? 
I will add some tests to this projects as soon as I have some time. For now, you can make a pull request with this feature please.

**Comment by drwlrsn** [comment]
@DiogoMarques29 I am currently using wagtail-embedvideos with a custom image model. I could totally add some tests. Testing with Django/Wagtail is not something I am very knowledgeable about; however, it's something I would like to learn. I'll try and see what I can do.

**Comment by drwlrsn** [comment]
Okay drwlrsn/wagtail-embedvideos@cb006c9f4d48a37c51ae5ed5dc43b034ebf87534 implements a very simple test to make sure the custom image model is being used if defined. I tried to actually verify that `EmbedVideo.thumbnail.field.rel.to` returns the custom image model. However, without a migration (I think) it just returns a string rather than an object. 

I am still pretty new at Django, but I think `contenttypes` might be something worth looking at.

**Comment by SalahAdDin** [comment]
@drwlrsn , if i'm not wrong, i added support for a custom thumbnail in this https://github.com/infoportugal/wagtail-embedvideos/pull/56 PR.
You can review it in my fork.

@DiogoMarques29 Can you review it?

**Comment by DiogoMarques29** [comment]
With the introduction of Embedded Content in wagtail 1.12 https://docs.wagtail.io/en/v1.12.6/releases/1.12.html#improved-embed-configuration, this package will no longer be maintained.

**Comment by bashu** [comment]
to @drwlrsn let me know if it was not fixed in `wagtail-embedvideos>=0.5`
