### ISSUE TITLE
Document urllib3 as a requirement for python3

### ISSUE THREAD

**Issue by akhayyat** [bashu/wagtail-embedvideos#21]
When using python 3, I get the following error:

``` pytb
wagtail_embed_videos/models.py",
 line 7, in <module>
    import urllib3
ImportError: No module named 'urllib3'
```

which goes away if the third-party package `urllib3` is installed.

Perhaps it should be mentioned in the installation instructions that `urllib3` is a requirement if you are using python3.

**Comment by drwlrsn** [comment]
Hey @akhayyat this is a great find. I should be able patch the imports so there is no dependency on urllib3. I am just working on a test (not my strongest skill at the moment) and should have a pull request ready in the next day or so.

**Comment by SalahAdDin** [comment]
:+1:
