### ISSUE TITLE
Create EmbedVideoBlock for StreamFields

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#33]
Hi man, 

Taking advantage for new `wagtail` features, what do you think about create a `EmbedVideoBlock` for add in `StreamFields` feature?

**Comment by SalahAdDin** [comment]
Oh yeah, it exist, but, why not create his properly documentation? People wants to know how use `EmbedVideo` blocks :D

**Comment by davejacobs** [comment]
What's the best way to use this block? I tried adding it to my site, but it just renders the embedded video title.

**Comment by davejacobs** [comment]
How can we take advantage of the `EmbedVideoChooserBlock`? All I can get it to do is display the video title.

**Comment by SalahAdDin** [comment]
@DiogoMarques29 What's up man?

**Comment by SalahAdDin** [comment]
@DiogoMarques29 https://github.com/infoportugal/wagtail-embedvideos/pull/55, this PR add support for _**StreamBlocks**_.
