### ISSUE TITLE
Cloning github repository install incomplete package

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#4]
Man, i had installed this package cloning with pip but don't install full this package and i don't know why:
![no instala paquete completo](https://cloud.githubusercontent.com/assets/5034215/9223508/662545d8-40c0-11e5-9e21-5c27e1915ba5.png)
Do you know why happen this?

**Comment by DiogoMarques29** [comment]
Avaiable in release 0.1

**Comment by SalahAdDin** [comment]
No man, wait, i have two improvements for this app :D

**Comment by SalahAdDin** [comment]
Wow, in my server happens that install wit pip git but templates isn't in the installation folder!

**Comment by SalahAdDin** [comment]
This bug persist until now!

**Comment by SalahAdDin** [comment]
Hi man, what's about pip package?

**Comment by SalahAdDin** [comment]
@rmartins90 Hi, when we'll can install it from pip?

**Comment by DiogoMarques29** [comment]
@SalahAdDin hi, you can install it via pip:

```
pip install wagtail-embed-videos
```
