### ISSUE TITLE
can only concatenate list (not "tuple") to list

### ISSUE THREAD

**Issue by emg36** [bashu/wagtail-embedvideos#40]
I just updated all my packages this morning and came across this error - TypeError: can only concatenate list (not "tuple") to list at wagtail_embed_videos/models.py, line 104

search_fields = TagSearchable.search_fields + (
        index.FilterField('uploaded_by_user'),
    )

I needed to change to the below for it to fix.

search_fields = TagSearchable.search_fields + [
        index.FilterField('uploaded_by_user'),
    ]

**Comment by SalahAdDin** [comment]
my long, long pull request solve it.

**Comment by PaulWGraham** [comment]
To add a little more info, using a tuple for search fields went from deprecated in wagtail 1.6.3 to straight broken in wagtail 1.7. This means that the current version of wagtail will not work with the current version wagtail-embedvideos. The following is a snippet of the error that happens if you try:

> File "/usr/local/lib/python2.7/dist-packages/wagtail_embed_videos/models.py", line 78, in <module>
> 
> class AbstractEmbedVideo(models.Model, TagSearchable):
> 
> File "/usr/local/lib/python2.7/dist-packages/wagtail_embed_videos/models.py", line 104, in 
> 
> AbstractEmbedVideo
>     index.FilterField('uploaded_by_user'),
> 
> TypeError: can only concatenate list (not "tuple") to list

**Comment by SalahAdDin** [comment]
@PaulWGraham please, review my pr, it's completly!

**Comment by SalahAdDin** [comment]
https://github.com/infoportugal/wagtail-embedvideos/pull/56 solve this, i think.
@emg36 You can review my fork while @DiogoMarques29 merge this pr.
