### ISSUE TITLE
Getting a 500 error in the admin when using the chooser

### ISSUE THREAD

**Issue by bmoe872** [bashu/wagtail-embedvideos#45]
# My Setup
- Ubunutu 16.04
- Jquery 3.2.0
- Django 1.11
- Wagtail 1.10
- Jinja2 for front facing templates, but Django Templates for admin. (as per the wagtail guide)

# My Model Definition:
```
class SomePage(Page):
    video= models.ForeignKey( ... stuff from example ... )

    content_panels = Page.content_panels + [
        EmbedVideoChooserPanel('video),
    ]
```

When I click on the Chooser I get a 500 error in the console:
`jquery-2.2.1.min.js:4 GET http://localhost:5000/admin/embed_videos/chooser/ 500 (INTERNAL SERVER ERROR)`

And it does not open up the chooser at all.

# Things I've tried
I tried bringing back my version of Jquery to 2.2.1 - That didn't work

Any help is appreciated.

**Comment by SalahAdDin** [comment]
Try to reinstall it, if it doesn't works try with my fork, is more updated.

**Comment by SalahAdDin** [comment]
@bmoe872 Did you try with my fork?

**Comment by bmoe872** [comment]
@SalahAdDin we ended up opting towards using the embedded function through the RichTextField.

**Comment by SalahAdDin** [comment]
@bmoe872 I'm sorry man, my fork have streamblocks and other usefull new features.
@DiogoMarques29 It's a fault that PR aren't merged yet.
