### ISSUE TITLE
Can't reliably create multiple word tags

### ISSUE THREAD

**Issue by brianedelman** [bashu/wagtail-embedvideos#47]
Using most recent version of wagtail-embedvideos 0.3.2 and wagtail 1.10.1.

Recently Wagtail allowed for multiple word tags. This is a feature that isn't achievable in the tagging of embedded videos. However, if I put the tag in quotes it will work. I have noticed, however, that often times it will look like it worked and register the full tag as "Keepin it Real" but after saving, it splits them into seperate tags: "Keepin", "it", and "Real". I have been able to reliably make it work if I also add another multiple word tag after the first one. So "Keepin it Real" and "Other Tag" allows both tags to be saved correctly.

**Comment by SalahAdDin** [comment]
@brianedelman , can you make a PR for this feature? or maybe provide the code's part that allow multiple words tags. 

I can help you.

**Comment by DiogoMarques29** [comment]
With the introduction of Embedded Content in wagtail 1.12 https://docs.wagtail.io/en/v1.12.6/releases/1.12.html#improved-embed-configuration, this package will no longer be maintained.

**Comment by bashu** [comment]
to @brianedelman please try `wagtail-embedvideos>=0.5`

![thehoff](https://user-images.githubusercontent.com/144783/140690331-64b75520-a0db-40fb-ae4b-87b49df31186.gif)
