### ISSUE TITLE
[Featured]Ability to reproduce a embed video in wagtail admin

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#5]
Will be great can play the embed videos in wagtail admin to ensure that is the video we want to embed, like we can do with django-embed-video using AdminVideoMixin.

We could take advantage of the big thumbnail video and put in his place a video player.
![reproducirvideo](https://cloud.githubusercontent.com/assets/5034215/9239760/7051ae70-4124-11e5-8a15-ba54dfb68f01.png)
And, maybe you will want put locale files for dinamic language translation.

**Comment by DiogoMarques29** [comment]
Hi,
Yes, that is a great idea. Will be implemented when we have some time.
About the locale files, will add them in a stable release.

**Comment by SalahAdDin** [comment]
Here :D https://github.com/infoportugal/wagtail-embedvideos/pull/6
