### ISSUE TITLE
Wagtail 2.0, Django 2.0

### ISSUE THREAD

**Issue by benpetty** [bashu/wagtail-embedvideos#58]
Any plans to update this package to work with the latest Wagtail & Django versions?

**Comment by jordanmt** [comment]
I just wondered the same, and I've gotten pretty far by updating the wagtail namespace changes, ensuring on_delete is set on model foreign keys, and reflecting the change to django.core.urlresolver (now django.urls).

As it turns out, there is a pull request with (at least) those changes: #60

**Comment by emg36** [comment]
Need to update the edit_handlers.py to include the following to avoid the errors 

`required_fields() missing 1 required positional argument: 'self'`
and
`required_formsets() missing 1 required positional argument: 'self'`


class BaseEmbedVideoChooserPanel(BaseChooserPanel):
...
    @classmethod
    def required_fields(self):
        return []

    @classmethod
    def required_formsets(self):
        return {}
...

**Comment by jordanmt** [comment]
Actually, it looks like [the edit_handlers API has been simplified](https://github.com/wagtail/wagtail/issues/4377) 2.0. Might be sufficient to replace the two classes with one:
```
class EmbedVideoChooserPanel(BaseChooserPanel):
    object_type_name = "embed_video"

    def widget_overrides(cls):
        return {
            cls.field_name: AdminEmbedVideoChooser
        }
```

**Comment by DiogoMarques29** [comment]
New version 0.4.0 now supports django and wagtail 2.0
