### ISSUE TITLE
Renamed wagtail_embed_videos to wagtail.embedvideos

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#8]
I think that change the package name for one more elegant name will be better.
In wagtail are doing this, see: https://github.com/torchbox/wagtail/pull/1498

Anyone have some ideas for this great app?

**Comment by DiogoMarques29** [comment]
Hi, for now I think this name is just fine. Some day if this app is integrated within wagtail, a name change will be considered.
